# Generated by Django 5.1.1 on 2024-09-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenresModel',
            new_name='GenreModel',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.genremodel', verbose_name='Genres'),
        ),
    ]
